### ISSUE TITLE
CurieUtil import fails

### ISSUE THREAD

**Issue by pbordron** [geneontology/gocam-sif-pyexport#5]
The `src` dir from CurieUtil must be in the gocam-sif-pyexport root directory.

https://github.com/geneontology/gocam-sif-pyexport/blob/daa6b613270be8abdc2fc74d3b6f0abb1d0bcf4e/ttl2sif.py#L15

Can you fix it?

**Comment by NeginBabaiha** [comment]
Could any one fix it?

**Comment by kltm** [comment]
@pbordron @NeginBabaiha 
My apologies for a slow response here.
As of this writing, this software is not really supported by the GO. We're currently re-evaluating how we want to model data for exports and will likely archive this repo in the new year. If you could let us know a little about your use cases, we might be able to direct you to better options, or at least allow us to better serve your use cases in the next iteration of this type of light export.

@dustine32 When you get back, I just wanted to check with you that this isn't used anymore elsewhere, right? IIRC, this was only used for the (now defunct) GO-CAM downloads?

**Comment by NeginBabaiha** [comment]
Thanks for replying. I would like to work with all GO-CAM statements available. For this purpose, would you recommend me to use the available .sif files, or shall I work with Turtle files?

**Comment by kltm** [comment]
Talking to @dustine32 , this code does seem to be deprecated and no longer supported or used.
